namespace: yash-ns

names:
  deployment: retail-deployment
  statefulset: retail-mongodb
  mongodbService: mongodb
  retailService: retail-service
  configmap: retail-app-config
  secret: retail-app-secret
  storageClass: retail-sc
  pvc: retail-mongodb-pvc

labels:
  retailApp: retail
  mongodb: mongodb

deployment:
  replicas: 4
  containerName: retail-container
  port: 3130

statefulset:
  replicas: 3
  containerName: mongodb
  port: 27017
  storageSize: 1Gi

image:
  retail:
    repository: saiteja2502/userprofileretail
    tag: latest
  mongodb:
    repository: mongo
    tag: latest

service:
  retail:
    type: LoadBalancer
    port: 3130
  mongodb:
    port: 27017

config:
  MONGODB_URI: mongodb://mongodb:27017/myDatabase
  SESSION_SECRET: "1234"
  PORT: "3130"
  MONGO_INITDB_DATABASE: myDatabase

secret:
  EMAIL_USER: chagantyteja2502@gmail.com
  EMAIL_PASS: yxoq bjuk rdnt alzp

storageClass:
  provisioner: ebs.csi.aws.com
  type: gp3
  reclaimPolicy: Retain
  volumeBindingMode: WaitForFirstConsumer

pvc:
  size: 2Gi