apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.names.deployment }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.labels.retailApp }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.retailApp }}
    spec:
      containers:
      - name: {{ .Values.deployment.containerName }}
        image: "{{ .Values.image.retail.repository }}:{{ .Values.image.retail.tag }}"
        ports:
        - containerPort: {{ .Values.deployment.port }}
        envFrom:
        - configMapRef:
            name: {{ .Values.names.configmap }}
        - secretRef:
            name: {{ .Values.names.secret }}