apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.names.mongodbService }}
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.labels.mongodb }}
  ports:
    - port: {{ .Values.service.mongodb.port }}
      targetPort: {{ .Values.statefulset.port }}