apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.names.retailService }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.labels.retailApp }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.retail.port }}
      targetPort: {{ .Values.deployment.port }}
  type: {{ .Values.service.retail.type }}
