namespace: yash-ns

deployment:
  replicas: 5
  containerName: retail-container
  containerPort: 3130
  label: retail

stateful:
  replicas: 1
  containerName: mongodb
  containerPort: 27017
  label: mongodb
  volumeName: mongo-volume
  mountPath: /data/db
  accessMode: ReadWriteOnce
  storageSize: 1Gi
  storageClassName: retail-app-storageclass

image:
  repository: saiteja2502/userprofileretail
  tag: latest
  mongodb:
    repository: mongo
    tag: latest

service:
  retail:
    type: LoadBalancer
    port: 3130
    protocol: TCP
  mongodb:
    port: 27017
    protocol: TCP
    clusterIP: None

config:
  MONGODB_URI: mongodb://retail-app-mongodb-svc:27017/myDatabase
  SESSION_SECRET: "1234"
  PORT: "3130"
  MONGO_INITDB_DATABASE: myDatabase

secret:
  type: Opaque
  EMAIL_USER: Y2hhZ2FudHl0ZWphMjUwMkBnbWFpbC5jb20=
  EMAIL_PASS: eXhvcSBianVrIHJkbnQgYWx6cA==

env:
  MONGODB_URI: MONGODB_URI
  SESSION_SECRET: SESSION_SECRET
  PORT: PORT
  EMAIL_USER: EMAIL_USER
  EMAIL_PASS: EMAIL_PASS
  MONGO_INITDB_DATABASE: MONGO_INITDB_DATABASE

pvc:
  storage: 2Gi

storageClass:
  provisioner: ebs.csi.aws.com
  type: gp3
  reclaimPolicy: Retain
  volumeBindingMode: WaitForFirstConsumer
