apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: retail-mongodb-pvc
  namespace: yash-ns
spec:
  accessModes:  
    - ReadWriteOnce 
  resources:
    requests:
      storage: 2Gi  
  storageClassName: retail-sc 
